#!/usr/bin/env bash
#cd "$(dirname "$0")"

echo -e Choose option "\\n1. debug\\n2. errors\\n3. git pull\\n4. email test\\n5. email test(Stage)\\n6. clean cache\\n7. newsletter"
read service_id
case $service_id in
     1)
          echo -e "¿Cuántas líneas?"
          read lines
          tail -f -n $lines ./app/tmp/logs/debug.log
          ;;
     2)
          echo -e "¿Cuántas líneas?"
          read lines
          tail -f -n $lines ./app/tmp/logs/error.log
          ;;
     3)
          git pull
          ;;
     4)
          echo -e "Que email quiere probar?"
          read email
          wget https://chatelet.com.ar/shop/test_email/$email &> /dev/null
          ;;
     5)
          echo -e "Que email quiere probar (Stage)?"
          read email
          wget https://test.chatelet.com.ar/shop/test_email/$email &> /dev/null
          ;;
     6)
          echo -e "Que limpiar cache?"
          sudo rm -rf ./app/tmp/cache/persistent/myapp* && sudo rm -rf ./app/tmp/cache/models/myapp*
          ;;
     7)
          echo -e "¿Cuántas líneas?"
          read lines
          tail -f -n $lines /var/www/chatelet/app/tmp/logs/newsletter.log
          ;;
esac

printf "success\n"